### ISSUE TITLE
Mistakes in data/time_to_impact.csv

### ISSUE THREAD

**Issue by ilya-pauzner** [yuval-harpaz/alarms#4]
The file [data/time_to_impact.csv](https://github.com/yuval-harpaz/alarms/blob/master/data/time_to_impact.csv) contains some mistakes.
To spot them, one can visualize the locations and their time to impact on a map.
![image](https://github.com/user-attachments/assets/a01a6559-da0e-49ad-b431-24b69ee54bd2)
An example of such a mistake:
 עמנואל has 15 seconds to impact in file, but on the פיקוד העורף it is stated that it has 90 seconds, like all its neighbors.
![image](https://github.com/user-attachments/assets/0cad6611-836e-419c-be84-ec6e7509d144)
![image](https://github.com/user-attachments/assets/7dad6bb4-a3d9-444c-bc3d-b408f57307c9)
![image](https://github.com/user-attachments/assets/9239283b-fe94-41a4-840b-e0c1325fb547)
 
Code to reproduce:
```python
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import folium
```

```python
dist = pd.read_csv('https://raw.githubusercontent.com/yuval-harpaz/alarms/refs/heads/master/data/coord_km_gaza.csv')
time = pd.read_csv('https://raw.githubusercontent.com/yuval-harpaz/alarms/refs/heads/master/data/time_to_impact.csv')
time['seconds'] = time.alarm_time.map({
    'מיידי': 0,
    '15 שניות': 15,
    '30 שניות': 30,
    '45 שניות': 45,
    'דקה': 60,
    'דקה וחצי': 90,
    '3 דקות': 180
})
combined = time.merge(dist, left_on='cities', right_on='loc')
colors = {
    0: 'red',
    15: 'blue',
    30: 'gray',
    45: 'darkred',
    60: 'lightred',
    90: 'orange',
    180: 'beige',
}

m = folium.Map(location=(31.5, 35), zoom_start=8)
combined.apply(lambda row: folium.Marker((row['lat'], row['long']), icon=folium.Icon(color=colors[row['seconds']]), tooltip=row['cities'] + ' ' + str(row['seconds'])).add_to(m), axis=1)
m
```

**Comment by yuval-harpaz** [comment]
I updated the table, it was never in use so I did not maintain it. It may require splitting for alarms that are clustered by Pikud HaOref
